import "~/styles/globals.css";

import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNavbar() {
  return (
    <nav className=" p-5 text-white">
      <div className="flex justify-between w-full max-w-6xl mx-auto">
       
          <Link href="/" className="text-2xl font-bold text-white">
            Gallery
          </Link>
          <Link href="/" className="text-2xl font-bold text-white">
           SignIn
          </Link>
      
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TopNavbar />
        {children}
      </body>
    </html>
  );
}
